name: jaguar_facebook_client
description: Facebook client for Dart from Jaguar authors
version: 0.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_facebook_client

environment:
  sdk: ">=1.8.0 <2.0.0"

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  oauth2:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
